// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PS11905_BAODUONG_ASMFULL_NET104.Models;

namespace PS11905_BAODUONG_ASMFULL_NET104.Migrations
{
    [DbContext(typeof(webglab_dbsContext))]
    partial class webglab_dbsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PS11905_BAODUONG_ASMFULL_NET104.Models.ChiTietHD", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("IDHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("ChiTietHD");
                });

            modelBuilder.Entity("PS11905_BAODUONG_ASMFULL_NET104.Models.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("PS11905_BAODUONG_ASMFULL_NET104.Models.NhomSp", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhom")
                        .HasName("PK__NhomSP__234F91CD18CF969F");

                    b.ToTable("NhomSP");
                });

            modelBuilder.Entity("PS11905_BAODUONG_ASMFULL_NET104.Models.Sanpham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaSP")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("money");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("MoTaSp")
                        .HasColumnName("MoTaSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhomSp")
                        .HasColumnName("NhomSP")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasColumnName("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSp")
                        .HasName("PK__SANPHAM__2725081CA68D9066");

                    b.HasIndex("NhomSp");

                    b.ToTable("SANPHAM");
                });

            modelBuilder.Entity("PS11905_BAODUONG_ASMFULL_NET104.Models.Sanpham", b =>
                {
                    b.HasOne("PS11905_BAODUONG_ASMFULL_NET104.Models.NhomSp", "NhomSpNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("NhomSp")
                        .HasConstraintName("FK__SANPHAM__NhomSP__267ABA7A")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
